name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: DivyanshuRishi
          outputs: dist
      - name: Upload snake animation
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake.svg
          path: dist/github-contribution-grid-snake.svg
